name: Run integration tests on GCP
on:
  push:
    branches:
      - main
  # Trigger from this repository manually
  workflow_dispatch:

# Just invoke the reusable one with the repo values
jobs:
  run-integration-gcp:
    uses: calyptia/fluent-bit-ci/.github/workflows/reusable-integration-test-gcp.yaml@main
    secrets:
      grafana_username: ${{ secrets.GRAFANA_USERNAME }}
      terraform_api_token: ${{ secrets.TF_API_TOKEN }}
      gcp_service_account_key: ${{ secrets.GCP_SA_KEY }}
      grafana_password: ${{ secrets.GRAFANA_PASSWORD }}