name: Run integration tests on GCP
on:
  push:
    branches:
      - main
# Just invoke the reusable one with the repo values
jobs:
  run-integration-gcp:
    uses: calyptia/fluent-bit-ci/.github/workflows/reusable-integration-test-gcp.yaml@main
    with:
      image-name: fluentbitdev/fluent-bit
      image-tag: x86_64-master
    secrets:
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
      GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
      GRAFANA_USERNAME: ${{ secrets.GRAFANA_USERNAME }}
      GRAFANA_PASSWORD: ${{ secrets.GRAFANA_PASSWORD }}